### ISSUE TITLE
Issue when selecting something!

### ISSUE THREAD

**Issue by AlexNodex** [ouroboroscoding/react-native-picker#2]
You specified `onScroll` on a <ScrollView> but not `scrollEventThrottle`. You will only receive one event. Using `16` you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.

**Comment by ouroboroscoding** [comment]
Hi Alex, scrollEventThrottle is only available on iOS, and I have not had the chance to test on that platform, so I am not aware of whatever this issue is. Please feel free to make a pull request with the necessary changes and I will update the repo.

**Comment by ouroboroscoding** [comment]
This is fixed in 0.3.1 which was just pushed and published
