### ISSUE TITLE
Solution for LOG message on ios.

### ISSUE THREAD

**Issue by jo2b54** [ouroboroscoding/react-native-picker#3]
Hello, i have tested this solution on both IOS and ANDROID.
Just add the prop scrollEventThrottle={0} on the line "ScrollView"
                            "ScrollView bounces={false} onScroll={scrolled} scrollEventThrottle={0}
                                ref={scrollSet} style={styles.items}"

**Comment by ouroboroscoding** [comment]
This is fixed in 0.3.1 which was just pushed and published
