### ISSUE TITLE
Suggestion of new parameters

### ISSUE THREAD

**Issue by jo2b54** [ouroboroscoding/react-native-picker#4]
I would like to suggest two modifications that i tested on Expo.
Make possible to have a parameter to specify the ITEM_HEIGHT property (I prefer 60 than 40) and the fontSize of the itemText (22 instead of 18)
Add a placeholder property (defined by a parameter) to the TextInput in View pointerEvents.

It should be great. Thanks.

**Comment by ouroboroscoding** [comment]
This is done in the 0.3.0 release which was just pushed and published. Thank you for the suggestion, and sorry it took me so long to get to it.
